### ISSUE TITLE
still compatible ?

### ISSUE THREAD

**Issue by bvandenbon** [7leads/ngx-cookie-service#55] opened 2018-12-27 01:05 UTC
Correct me if I'm wrong, but this service is not compatible with the latest angular versions is it ?

I am having the following errors:

    Uncaught Error: Can't resolve all parameters for CookieService: (?, [object Object])

Which seems to make perfect sense, because indeed, if you look at the signature of the constructor of this service, it does take 2 parameters. And I have no idea where this information should come from.

Then secondly, there is the following error, (possibly related to the previous one): 

    /~/ngx-cookie-service/cookie-service/cookie.service.js 145:59-67 "export 'DOCUMENT' was not found in '@angular/common'

That seems to imply that something has changed in the `@angular/common` libs, right ?

At first I was running on angular 4, and now just upgraded to angular 7. 
I had the exact same error messages with both versions.

**Comment by faisalike** [comment] 2019-01-02 09:30
i'm using with angular 7 working fine.

**Comment by CunningFatalist** [comment] 2019-01-03 13:37
Hello,

it's working for me. Could you set up a small test project with a reproduction of the error? Also, have you tried `rm -rf node_modules && npm install`? That always seems to solve a huge variety of issues like this.

Cheers

**Comment by cristtopher** [comment] 2019-01-07 15:18
i'm using with angular 7 too.  All ok.

**Comment by CunningFatalist** [comment] 2019-01-08 06:57
Hello,

since no one else seems to have problems with this, and I cannot reproduce it, I will close this issue.

Cheers

**Closed by CunningFatalist** 2019-01-08 06:57 UTC
Labels: cannot reproduce
